### ISSUE TITLE
game crash after last game update (STONE BLOCK 2)

### ISSUE THREAD

**Issue by horse142029** [Seshpenguin/minetogether-standalone#1]
[crash-2019-07-08_21.06.49-server.txt](https://github.com/Seshpenguin/minetogether-standalone/files/3368924/crash-2019-07-08_21.06.49-server.txt)

Please help me this mod crash 3 times on me.

**Comment by Seshpenguin** [comment]
Hi! This is repo is seperate from the MineTogether mod. ( This is designed for server owners using MineTogether).

You will probably want to file a bug report on the Stone block 2 repo or the MineTogether repo.
