### ISSUE TITLE
game crash after last game update (STONE BLOCK 2)

### ISSUE THREAD

**Issue by horse142029** [Seshpenguin/minetogether-standalone#2]
[crash-2019-07-08_21.06.25-client.txt](https://github.com/Seshpenguin/minetogether-standalone/files/3373154/crash-2019-07-08_21.06.25-client.txt)

**Comment by Seshpenguin** [comment]
Hi, again...

**This repository is not a Minecraft Mod!** This is an external piece of server software that is designed to *interact* with MineTogether, but not on a client context!

This is probably the repository you are looking for: https://github.com/CreeperHost/CreeperHostGui
